version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT_POSTGRES}:5432"

  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_INTERNAL_URL: ${KEYCLOAK_INTERNAL_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - postgres
      - keycloak
    ports:
      - "${PORT_BACKEND}:8080"

  frontend:
    build: ./frontend/web_lab4_frontend
    ports:
      - "${PORT_FRONTEND}:80"
    depends_on:
      - backend

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "${PORT_KEYCLOAK}:${PORT_KEYCLOAK}"
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_PORT: ${PORT_KEYCLOAK}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL_DATABASE: keycloak
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      - keycloak-postgres
    command:
      "start-dev --http-port=${PORT_KEYCLOAK} --hostname-strict=false --http-enabled=true"

  keycloak-postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "${PORT_KC_DB}:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  keycloak_postgres_data: