#spring.config.import=file:.env[.properties]

spring.application.name=web_lab4

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/web_lab4_db
spring.datasource.username=maxkarn
spring.datasource.password=maxkarn
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (8h)
app.jwt.secret=666JNFKDHFKLDK:jkjf;ldsjfosdijfu943hpfihuifhdsihfdjghoi;dfhg87fhu;gfyhgisfhgudshfuGUPHFuhdfhiphfsdhfdjfh;kdshfsd
app.jwt.token_expiration=28800000
app.jwt.refresh_token_expiration=252000000
